Re-structure Knative and Istio YAML manifests usage and storage
vhive-serverless/vHive pull request #594
Opened 2022-09-02 14:05 UTC by ustiugov

## Summary

Previously, we fetched the Knative & net-istio YAML files for container-based  deployments from Internet because we never had to change them. Instead, we decided to store these files in the repo (and tweak them if necessary, using the `yq` tool). Hence, I moved the vHive-specific and stock YAML files to `configs/knative_yamls/{vhive, stock}/` folders, correspondingly. 

Other changes in this PR:
* Changed the pod network IP address (CIDR) range, as the previous range overlapped with other services in CloudLab. Authored by @HongyuHe 
* Untaint the master node to allow "control plane" services (namely, Istio, Knative activator, autoscaler, and others) to be scheduled on the master node. The reason for this is that the master node in our experiments is underutilized and moving these services there should increase measurement accuracy. We may revisit this decision in future, e.g., in case the master node faces overload.

## Warning :warning:

We noticed that pod network IP range might need to be chosen differently for different cluster infrastructure. As we mostly use CloudLab for these experiments, we fine-tuned the range to its configuration. We encourage the vHive users to report any problems they face related to the IP range selection to make vHive setup more general.

2022-09-05 17:08 UTC, ustiugov commented
@HongyuHe could you please review the auto-generated YAML files? The generation script will be moved to the loader repo so it is there only for reference.

2022-09-07 17:46 UTC, HongyuHe commented
> @HongyuHe could you please review the auto-generated YAML files? The generation script will be moved to the loader repo so it is there only for reference.

Thank you very much indeed! 

But as I said, I can't tell whether it works or not by just eyeballing, since I don't remember everything by heart. 

The original setup in loader has been used in practice a zillion times, and it works. So please examining it by setting up clusters e2e and run experiments with the loader.

Thanks again!

2022-09-07 17:54 UTC, ustiugov commented
Thank you. I will test everything, no worries

2022-09-08 08:07 UTC, cvetkovic requested changes

2022-09-08 08:07 UTC, cvetkovic commented on scripts/utils/turbo_boost.sh
> +#!/usr/bin/env bash
The path to this script seems wrong. In the loader repo, the address is `scripts/turbo_boost.sh`. What should we do in the end?

2022-09-08 08:14 UTC, cvetkovic commented on scripts/utils/turbo_boost.sh
> +#!/usr/bin/env bash
Ignore this comment. I have just seen that you changed the path on the new PR to my PR.

2022-09-08 08:15 UTC, cvetkovic submitted a review, later dismissed

2023-12-27 07:02 UTC, leokondrashov commented
Replaced by #888.

2023-12-27 07:02 UTC, closed without merging