When pulling images check for stale cached images
vhive-serverless/vHive pull request #624
Opened 2022-10-13 17:34 UTC by biecho

## Summary

When vHive does pull images, it must check in its local cache if an image is stale. vHive should do this without pulling the whole image again. `skopeo` is used to only inspect the metadata from a remote image.

2022-10-13 18:16 UTC, ustiugov reviewed
looks good! however, I am afraid that the image check check would slow down the system if used by default. @biecho could you please measure the added overhead? you can use timestamps printed within log messages, we just need an estimate.

2022-10-14 10:15 UTC, biecho commented
> looks good! however, I am afraid that the image check check would slow down the system if used by default. @biecho could you please measure the added overhead? you can use timestamps printed within log messages, we just need an estimate.

Done

2022-10-14 13:03 UTC, ustiugov commented
@biecho great! could you please publish the measurements in this PR? 

also, could you please take a look at the test failures (must be very simple), particularly vHive unit tests/ [misc, taps, ...]. The failure is likely due to the repo migration last week. I would really appreciate if you could help fix the problems.

2022-10-16 12:41 UTC, biecho commented
> @biecho great! could you please publish the measurements in this PR?
> 
> also, could you please take a look at the test failures (must be very simple), particularly vHive unit tests/ [misc, taps, ...]. The failure is likely due to the repo migration last week. I would really appreciate if you could help fix the problems.

Sure I'll publish the measurements as soon as possible. Regarding the vHive unit/tests, I see the following in the logs:

```

2022-11-04 17:22 UTC, cvetkovic requested changes

2022-11-04 17:22 UTC, cvetkovic commented on ctriface/iface.go
> +	remoteImageDigest, err := remoteImageDigest(imageUrl)
Check for err and dump the error message.

2022-11-04 17:22 UTC, cvetkovic commented on ctriface/iface.go
> +	if !found || imageIsOutdated(image, imageUrl) {
Can you check how image staleness is checked in `containerd`? Clone the `containerd` repo and have a look into ContainerCreate stage of the sandbox creation in code, as well as in the logs. Containerd is already running on the worker node and you can check the performance of ContainerCreate phase in containerd logs. It should be creating queue-proxy container. Look into Estella's writing to see how to find logs.

2022-11-04 17:22 UTC, cvetkovic commented on ctriface/iface.go
> +	log.Printf("Remote digest fetching took %s", elapsed)
Debugf instead of Printf. If that is not available, switch to using logrus logging library.

2022-11-04 17:22 UTC, cvetkovic commented on ctriface/iface.go
> +	return o.pullRemoteImage(ctx, imageUrl)
One is for the local registry and the other is for the remote one. Is that correct?

2023-08-21 06:13 UTC, ustiugov commented
@cvetkovic do you guys still need this patch? if so, can someone take it over?

2023-08-21 09:55 UTC, closed without merging