Update quick start and developer's guide
vhive-serverless/vHive pull request #631
Opened 2022-11-01 12:23 UTC by ICantCodeForAnything

Add link to developer's guide in quick start guide for setting up one node stock only environment.
Add how to deploy functions to stock only environment.

2022-11-01 17:20 UTC, ustiugov requested changes
Thank you for the contribution! Please apply the changes, squash the commits into one (with `-s` non-capital s option for git) as per docs/contributing...md doc explains.

2022-11-01 17:20 UTC, ustiugov commented on docs/quickstart_guide.md
> +    > Deployer uses YAML files defined in configs/knative-workload that are **specific** to firecracker. Please refer to the [Developer's Guide](developers_guide.md) for deploying to a Stock Knative
```suggestion
    > Deployer uses YAML files defined in configs/knative-workload that are **specific** to firecracker. Please refer to the [Developer's Guide](developers_guide.md) for deploying functions in the container or gVisor based environment.
```

2022-11-01 17:20 UTC, ustiugov commented on docs/quickstart_guide.md
> +To see how to setup a one node cluster with stock-only or gVisor, see [Developer's guide](developers_guide.md).
```suggestion
To see how to setup a single node cluster with stock-only or gVisor, see [Developer's guide](developers_guide.md).
```

2022-11-01 17:20 UTC, ustiugov commented on docs/developers_guide.md
> +https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-python#yaml
```suggestion
To deploy a function in the stock or gVisor execution environment, please create and use your own YAML files following this [example](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-python#yaml)
```

2022-11-02 10:04 UTC, ICantCodeForAnything commented
I've applied the changes and squashed the commits :D

2022-11-03 08:48 UTC, ustiugov commented
Please fix the linter error: https://github.com/vhive-serverless/vHive/actions/runs/3376563816/jobs/5620875205#step:5:14

you need to sign off the commit with a particular format.

2022-11-03 12:22 UTC, ICantCodeForAnything commented
Ok I think I've signed it off now

2022-11-03 13:45 UTC, merged