Improved contributing_to_vhive.md: More detailed rationale and technique for Rebase & Merge
vhive-serverless/vHive pull request #793
Opened 2023-09-01 12:37 UTC by googlercolin

## Summary

Improved the descriptions in the "Rebasing on the Main Branch" and "Maintaining a Clean Main Branch & Avoiding Merge Commits" sections.

## Implementation Notes :hammer_and_pick:

* Provided an example of the consequence of a messy merge without rebasing
* Included `git checkout your-branch` in the instructions on how to rebase on main
* Included clearer motivations behind maintaining a clean main branch and avoiding merge commits

## External Dependencies :four_leaf_clover:

* N/A

## Breaking API Changes :warning:

* N/A

*Simply specify none (N/A) if not applicable.*

2023-09-04 05:37 UTC, yankai14 submitted a review, later dismissed

2023-09-05 03:04 UTC, leokondrashov commented
@googlercolin Please, sign your commit and update the branch.

2023-09-06 01:50 UTC, ustiugov requested changes

2023-09-06 01:52 UTC, ustiugov commented
Please sign the commit. 

BTW, do we mention the requirement to sign commits in the doc?

2023-09-06 05:12 UTC, googlercolin commented on docs/contributing_to_vhive.md
> +As you can see, your branch's commits (`A`, `B`, `C`) now build forward from the latest `main` commit (`G`). This linearizes the history and eliminates the need for merge commits.
Do you mean break line 98 into two lines? Would the same apply for other lines with several sentences? Or does this comment pertain only to this section?

2023-09-06 07:45 UTC, googlercolin commented
@ustiugov, I have signed the commit and pushed it here. The spellcheck linter is a bit weird because "linearizes" is an actual word in the Oxford dictionary. "Upstream's" was also flagged out. I've changed them nonetheless.

For the part on signing commits, I think I will make another PR to include it in the doc as it is not there at the moment.

2023-09-06 08:04 UTC, ustiugov requested changes
some lines are still too long

2023-09-08 07:58 UTC, ustiugov approved these changes

2023-09-08 07:58 UTC, merged