refactor easy_openyurt
vhive-serverless/vHive pull request #825
Opened 2023-09-18 10:03 UTC by lrq619

## Summary

Refactor [easy_openyurt](https://github.com/flyinghorse0510/easy_openyurt) into vHive

## Implementation Notes :hammer_and_pick:

* Implement a new package `node` to execute all remote commands through ssh
* `clean` 's functionality is currently not applicable, need to reload all instances after each deployment
* demo is now conducted mannually and needs to automate

## External Dependencies :four_leaf_clover:

* N/A

## Breaking API Changes :warning:

* N/A

*Simply specify none (N/A) if not applicable.*

2023-09-18 10:11 UTC, lrq619 commented
@jchua99 Please take a look at this branch, where I refactor easy_openyurt into vHive using go scripts, there're still some tasks for you to do:
1. Take a look at the `clean` function, which is implemented in `main.go: func cleanNodes()`, it will clean up setups in all the nodes so that the deployment can be simply re-run. However, its functionality is not working properly, currently the re-deployment will get stuck in `yurt.go:209` after clean , please try to make it work as expected.
2. Demo is now conducted manually, please add a `demo.go` to automate this procedure as described in README.md

2023-09-29 07:48 UTC, ustiugov requested changes
- [ ] fix inconsistent golang versions
- [ ] re-factor config parameters with appropriate JSON configs
- [ ] lint all the golang code (run `gofmt`)
- [ ] demo code should be separate from the code of the core/general toolchain. it is just a scenario script wich runs the general tool/scripts
- [ ] don't use `fmt.Print`, use the logger module
- [ ] add the vHive copyrights
- [ ] avoid script code duplication (e.g., for Knative setup, bash utils)
- [ ] replace YAML inlining into Golang files. Instead, have the YAML files and import them from the code

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/configs/knative.go
> +	KnativeVersion:           "1.9.2",
these configs should be taken from the vHive json config. there must be a consistent set of configs

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/configs/kube.go
> +	K8sVersion:                "1.25.9",
same here

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/configs/system.go
> +	GoVersion:                           "1.18.10",
same for this config. also make sure the golang version is the same as in the CI

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/configs/system.go
> +	KubectlVersion:                      "1.25.9-00",
avoid duplicate entries for the k8s version

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/go.mod
> +go 1.20
the CI uses 1.19 IIRC

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/configs/yurt.go
> +	KustomizeScriptDownloadUrl:      "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh",
what is this?

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/configs/yurt.go
> +	YurtVersion:                     "1.2.1",
should be in a JSON config

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/go.work
> +go 1.19
please make sure all golang versions are the same

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/logs/logs.go
> +	// _colorPurple = "\033[35m"
uncomment or clean up

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/main.go
> +func demo(deployerConfFile string){
demo-related stuff should be separate from the general tool

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/node/demo.go
> +	// cloud.yaml
elaborate

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/node/demo.go
> +	fmt.Printf("+Edge  Nodepool %s:\n", edgePoolName)
don't use `fmt`, use the logger library from Haoyuan (or the generic logger we use in the core vHive)

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/node/knative.go
> +// func (node *Node) ParseSubcommandKnative(args []string) {
clean up the commented code

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/node/knative.go
> +func (node *Node) InstallKnativeServing() {
these scripts are duplicates of the ones in vHive. also make sure that you use the same Knative configs (and the same versions!)

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/node/system.go
> +	logs.CheckErrorWithTagAndMsg(err, "Failed to dodify fstab!\n")
typo

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/template/template.go
> +var vHiveConfigsURL = "https://raw.githubusercontent.com/anshalshukla/vHive/release-1.9/configs"
I don't know what it is, but we should have everything in the repo, please fix

2023-09-29 07:48 UTC, ustiugov commented on scripts/openyurt_deployer/utils.go
> +func ExecShellCmd(cmd string, pars ...any) (string, error) {
I am quite sure these utils are the same as in the vHive scripts.

2023-11-01 08:02 UTC, leokondrashov commented
@lrq619 What is the status of this PR?

2023-11-01 13:30 UTC, lrq619 commented
> @lrq619 What is the status of this PR?

Waiting for a fyp to modify it, he will submit a PR tmr, I will handle it then

2023-11-10 06:26 UTC, lrq619 commented
@jchua99 Hello, please fix these testing failures on this branch

2023-11-17 15:41 UTC, leokondrashov commented
@lrq619 What is the status of this PR?

2023-11-17 15:43 UTC, lrq619 commented
> @lrq619 What is the status of this PR?

Should be closed now, Jason would push new PRs to replace this one

2023-11-17 15:43 UTC, closed without merging