Integrate UPF feature and tests
vhive-serverless/vHive pull request #883
Opened 2023-11-14 15:56 UTC by char-1ee

## Summary

Integrate the firecracker snapshot UPF features and enable UPF tests.

## Implementation Notes :hammer_and_pick:

* Enable UPF features and tests, refer to b6bfcbb7c6679fce46bbf69ddf2dc79dba759b8a
* Update firecracker-containerd image `default-rootfs.img`
* Update firecracker-containerd version 
* Update [kernel image](https://github.com/char-1ee/vHive/blob/400a49d284cb889e5eec377f28def74b85c0152d/scripts/setup_firecracker_containerd.sh#L49) firecracker-containerd used

## External Dependencies :four_leaf_clover:

* https://github.com/char-1ee/firecracker-containerd/tree/firecracker-v1.4.1-vhive-integration

## Breaking API Changes :warning:

* NA

*Simply specify none (N/A) if not applicable.*

2023-11-15 06:59 UTC, ustiugov commented
@char-1ee  Please fix the errors reported by the CI. 

@Ruiqi please assist with the runners if necessary. The kubectl error in the integration tests is strange

2023-11-15 06:59 UTC, ustiugov commented
@lrq619

2023-11-16 07:35 UTC, ustiugov commented on ctriface/iface_test.go
> -func TestMain(m *testing.M) {
don't delete testMain

2023-11-16 09:14 UTC, lrq619 commented
Hi @char-1ee I've already re-launched the runners, they should work fine now. But your codes still fail to pass these tests, please double check your codes and re-run the failed tests untill all of them are passed.

2023-12-11 03:51 UTC, ustiugov requested changes
- [ ] add the recompiled firecracker-container binaries
- [x] use gomft
- [x] other comments

2023-12-11 03:51 UTC, ustiugov commented on ctriface/iface.go
> +	fileBackend = "File"
run gofmt please

2023-12-11 03:51 UTC, ustiugov commented on ctriface/iface.go
>  			// FIXME (gh-807)
remove

2023-12-11 03:51 UTC, ustiugov commented on ctriface/iface_test.go
> -func TestMain(m *testing.M) {
applied?

2023-12-11 03:51 UTC, ustiugov commented on go.mod
> +	github.com/firecracker-microvm/firecracker-containerd => github.com/char-1ee/firecracker-containerd v0.0.0-20231018191519-49cac5eea134
don't forget to update our fork after testing

2023-12-11 03:51 UTC, ustiugov commented on scripts/github_runner/Dockerfile.github_runner
> +    sudo curl -fsSL -o /var/lib/firecracker-containerd/runtime/hello-vmlinux.bin https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/v1.5/x86_64/vmlinux-5.10.186
this requires redeployment of the self-hosted runners. please coordinate with Ruiqi.

2026-07-20 06:57 UTC, leokondrashov commented
superceeded by #1221

2026-07-20 06:57 UTC, closed without merging