Deploying Openyurt on top of kubernetes & knative
vhive-serverless/vHive pull request #887
Opened 2023-11-18 13:22 UTC by jchua99

## Summary

Deploying openyurt on top of initial configs of k8s and knative. 
To run, go build and ./openyurt_deployer deploy-yurt.

## Implementation Notes :hammer_and_pick:

* YurtMasterInit() init openyurt on master node
* masterNode info is extracted and stored into temp folder
* YurtMasterExpand() expands openyurt to workerNode
* temp folder is clean for all nodes

## External Dependencies :four_leaf_clover:

* 

## Breaking API Changes :warning:

* 

*Simply specify none (N/A) if not applicable.*

2023-12-13 06:33 UTC, ustiugov commented on scripts/openyurt-deployer/template/yurtTemplate.go
> +kind: Pod
replace with YAML

2023-12-20 06:22 UTC, lrq619 commented
Please add me as the reviewer, also, you only have two added checks here, but it should pass through all tests that was previously there

2023-12-21 11:30 UTC, lrq619 reviewed
Looks fine to me now, but make sure to delete the build binary file

2023-12-21 11:30 UTC, lrq619 commented on scripts/openyurt-deployer/openyurt_deployer
This binary file needs to be deleted

2023-12-21 12:00 UTC, ustiugov requested changes
- [ ] use Golang 1.19 everywhere. we should update it later to 1.20 but in a different PR
- [ ] add the vHive copyrights to all the source files
- [ ] I suggest making the whole deployer a single Golang module to make our life easier in future. We don't need moule versioning at this fine granularity. vHive can be a good example: it's a single module despite the folder structure. I suggesting having 1 module for vHive and 1 for deployer. No need for other modules, too complicated.
- [ ] remove binaries from the commit history (prune it! not just remove in a new commit)
- [ ] remove the YAML files duplication in golang files (I see 2 cases).

2023-12-21 12:00 UTC, ustiugov commented on scripts/openyurt-deployer/README.md
> +./openyurt_deployer kube
rename kube to `k8s`, more widely used

2023-12-21 12:00 UTC, ustiugov commented on scripts/openyurt-deployer/go.work
> +go 1.20
should be the same Goalng version everywhere

2023-12-21 12:00 UTC, ustiugov commented on scripts/openyurt-deployer/node/go.mod
> +go 1.20
1.19

2023-12-21 12:00 UTC, ustiugov commented on scripts/openyurt-deployer/node/knative.go
> +	_, err = node.ExecShellCmd("kubectl -n metallb-system wait deploy controller --timeout=900s --for=condition=Available")
seems too long. failed tests might take ages to die. consider a smaller value

2023-12-21 12:00 UTC, ustiugov commented on scripts/openyurt-deployer/node/node_test.go
> +
I'd say too many tests. in the future, you don't have to be that rigorous.

2023-12-21 12:00 UTC, ustiugov commented on scripts/openyurt-deployer/openyurt_deployer
and make sure it is removed from all the commits (otherwise the git repo becomes slower to fetch, etc). Use git commit --amend or a similar command to get rid of binaries in the commit history

2023-12-21 12:00 UTC, ustiugov commented on scripts/openyurt-deployer/template/yurtAppSetTemplate.go
> +	YurtAppSetTemplate = `echo 'apiVersion: apps.openyurt.io/v1alpha1
does it duplicate the YAML file in the same folder?

2023-12-21 12:00 UTC, ustiugov commented on scripts/openyurt-deployer/template/yurtTemplate.go
> +kind: Pod
remove the duplicate?

2023-12-29 04:25 UTC, merged