Fix firecracker related issues
vhive-serverless/vHive pull request #936
Opened 2024-02-12 20:26 UTC by JooyoungPark73

#931 **Error while deploying firecracker single-node deployment**
This issue is caused when migrating from bash script to go script. Did not change name properly.
https://github.com/vhive-serverless/vHive/blob/14f0b2d7ca9ab2a243063335c996e79d70349c5a/scripts/setup/setup.go#L91

---

#694 **required key GUEST_ADDR missing value**
This issue is caused by k8s version upgrade. After upgrade, they no longer support how we used to configure k8s before.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

2024-02-13 02:45 UTC, ustiugov requested changes
great! 

Please add "Fixes #936" to the PR description so it closes the issue

see the minor comment inline

P.S. for vHive's rather important changes, please ask me for a review too.

2024-02-13 02:45 UTC, ustiugov commented on scripts/utils/system.go
> +func CopyKernelToDirAndRename(source string, privileged bool) error {
I think this function is quite trivial, please inline it

2024-02-13 04:02 UTC, JooyoungPark73 commented
Ah I missed i opened an issue already. Yes.

2024-02-13 04:06 UTC, JooyoungPark73 commented
@leokondrashov Can you run them by yourself and check if it works properly?

2024-02-13 11:16 UTC, leokondrashov approved these changes
I've checked both single and multi-node setups; all work fine.

2024-02-14 09:26 UTC, ustiugov approved these changes

2024-02-14 09:26 UTC, merged